# name: Deploy to VPS

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Install Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "18"

#       - name: Install dependencies
#         run: npm ci

#       - name: Build project
#         env:
#           RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
#         run: |
#           echo "RESEND_API_KEY=$RESEND_API_KEY" >> .env
#           npm run build

#       - name: Deploy to VPS
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd ~/feet-on-the-go
#             git pull origin main
#             npm ci
#             echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
#             npm run build
#             pm2 restart feet-on-the-go
